from preprocessing.quantile_clipper import Identity, Clipper
from sklearn.preprocessing import LabelEncoder


numerical_features = [
     'piezo_station_investigation_depth',
     'piezo_station_altitude',
     'piezo_station_longitude',
     'piezo_station_latitude',
     'piezo_continuity_code',
     'piezo_producer_code',
     'meteo_id',
     'meteo_latitude',
     'meteo_longitude',
     'meteo_altitude',
     'meteo_rain_height',
     'meteo_DRR',
     'meteo_temperature_min',
     'meteo_time_tn',
     'meteo_temperature_max',
     'meteo_time_tx',
     'meteo_temperature_avg',
     'meteo_temperature_avg_threshold',
     'meteo_temperature_min_ground',
     'meteo_temperature_min_50cm',
     'meteo_frost_duration',
     'meteo_amplitude_tn_tx',
     'meteo_temperature_avg_tntm',
     'meteo_pressure_avg',
     'meteo_pression_maxi',
     'meteo_wind_speed_avg_10m',
     'meteo_wind_max',
     'meteo_wind_direction_max_inst',
     'meteo_time_wind_max',
     'meteo_wind_avg',
     'meteo_wind_direction_max_avg',
     'meteo_time_wind_avg',
     'meteo_wind_speed_avg_2m',
     'meteo_wind_max_2m',
     'meteo_wind_direction_max_inst_2m',
     'meteo_time_wind_max_2m',
     'meteo_wind_max_3s',
     'meteo_time_wind_max_3s',
     'meteo_humidity_min',
     'meteo_time_humidity_min',
     'meteo_humidity_max',
     'meteo_time_humidity_max',
     'meteo_humidity_duration_below_40%',
     'meteo_humidity_duration_above_80%',
     'meteo__pressure_saturation_avg',
     'meteo_wetting_duration',
     'meteo_humidity_avg',
     'meteo_sunshine_duration',
     'meteo_radiation',
     'meteo_radiation_direct',
     'meteo_sunshine_%',
     'meteo_radiation_IR',
     'meteo_radiation_UV_max',
     'meteo_cloudiness',
     'meteo_cloudiness_height',
     'meteo_if_snow',
     'meteo_if_fog',
     'meteo_if_thunderstorm',
     'meteo_if_sleet',
     'meteo_if_hail',
     'meteo_if_dew',
     'meteo_if_black_ice',
     'meteo_if_snow_ground',
     'meteo_if_frost',
     'meteo_if_smoke',
     'meteo_if_mist',
     'meteo_if_lightning',
     'meteo_evapotranspiration_grid',
     'meteo_radiation_UV',
     'meteo_snow_height',
     'meteo_snow_thickness_max',
     'meteo_snow_thickness_6h',
     'distance_piezo_meteo',
     'hydro_observation_result_elab',
     'hydro_status_code',
     'hydro_qualification_code',
     'hydro_longitude',
     'hydro_latitude',
     'distance_piezo_hydro',
     'prelev_volume_0',
     'prelev_longitude_0',
     'prelev_latitude_0',
     'prelev_commune_code_insee_0',
     'prelev_volume_1',
     'prelev_longitude_1',
     'prelev_latitude_1',
     'prelev_commune_code_insee_1',
     'prelev_volume_2',
     'prelev_longitude_2',
     'prelev_latitude_2',
     'prelev_commune_code_insee_2',
     'prelev_other_volume_sum',
]
TARGET = "piezo_groundwater_level_category"

dates_features = ['piezo_measurement_date',
                  'meteo_date',
                  'hydro_observation_date_elab']

categorical_features = [
     'piezo_obtention_mode',
     'piezo_status',
     'piezo_qualification',
     'hydro_hydro_quantity_elab',
     'prelev_usage_label_0',
     'prelev_volume_obtention_mode_label_0',
     'prelev_usage_label_1',
     'prelev_volume_obtention_mode_label_1',
     'prelev_usage_label_2',
     'prelev_volume_obtention_mode_label_2',
]

preprocessing_map = {
"piezo_station_department_code": LabelEncoder(),
"piezo_station_investigation_depth": Clipper(),
"piezo_station_altitude": Identity(),
"piezo_station_longitude": Identity(),
"piezo_station_latitude": Identity(),
"piezo_measurement_date": Identity(),
"piezo_obtention_mode": LabelEncoder(),
"piezo_status": LabelEncoder(),
"piezo_qualification": LabelEncoder(),
"piezo_continuity_code": Identity(),
"piezo_producer_code": Identity(),
"piezo_measure_nature_code": LabelEncoder(),
"meteo_id": Identity(),
"meteo_latitude": Identity(),
"meteo_longitude": Identity(),
"meteo_altitude": Identity(),
"meteo_date": Identity(),
"meteo_rain_height": Clipper(),
"meteo_DRR": Clipper(),
"meteo_temperature_min": Clipper(),
"meteo_time_tn": Identity(),
"meteo_temperature_max": Clipper(),
"meteo_time_tx": Identity(),
"meteo_temperature_avg": Clipper(),
"meteo_temperature_avg_threshold": Clipper(),
"meteo_temperature_min_ground": Clipper(),
"meteo_temperature_min_50cm": Clipper(),
"meteo_frost_duration": Clipper(),
"meteo_amplitude_tn_tx": Clipper(),
"meteo_temperature_avg_tntm": Clipper(),
"meteo_pressure_avg": Clipper(),
"meteo_pression_maxi": Clipper(),
"meteo_wind_speed_avg_10m": Clipper(),
"meteo_wind_max": Clipper(),
"meteo_wind_direction_max_inst": Clipper(),
"meteo_time_wind_max": Clipper(),
"meteo_wind_avg": Clipper(),
"meteo_wind_direction_max_avg": Clipper(),
"meteo_time_wind_avg": Clipper(),
"meteo_wind_speed_avg_2m": Clipper(),
"meteo_wind_max_2m": Clipper(),
"meteo_wind_direction_max_inst_2m": Clipper(),
"meteo_time_wind_max_2m": Clipper(),
"meteo_wind_max_3s": Clipper(),
"meteo_time_wind_max_3s": Clipper(),
"meteo_humidity_min": Clipper(),
"meteo_time_humidity_min": Clipper(),
"meteo_humidity_max": Clipper(),
"meteo_time_humidity_max": Clipper(),
"meteo_humidity_duration_below_40%": Clipper(),
"meteo_humidity_duration_above_80%": Clipper(),
"meteo__pressure_saturation_avg": Clipper(),
"meteo_wetting_duration": Clipper(),
"meteo_humidity_avg": Clipper(),
"meteo_sunshine_duration": Clipper(),
"meteo_radiation": Clipper(),
"meteo_radiation_direct": Clipper(),
"meteo_sunshine_%": Clipper(),
"meteo_radiation_IR": Clipper(),
"meteo_radiation_UV_max": Clipper(),
"meteo_cloudiness": Clipper(),
"meteo_cloudiness_height": Clipper(),
"meteo_if_snow": Identity(),
"meteo_if_fog": Identity(),
"meteo_if_thunderstorm": Identity(),
"meteo_if_sleet": Identity(),
"meteo_if_hail": Identity(),
"meteo_if_dew": Identity(),
"meteo_if_black_ice": Identity(),
"meteo_if_snow_ground": Identity(),
"meteo_if_frost": Identity(),
"meteo_if_smoke": Identity(),
"meteo_if_mist": Identity(),
"meteo_if_lightning": Identity(),
"meteo_evapotranspiration_grid": Clipper(),
"meteo_radiation_UV": Clipper(),
"meteo_snow_height": Clipper(),
"meteo_snow_thickness_max": Clipper(),
"meteo_snow_thickness_6h": Clipper(),
"distance_piezo_meteo": Clipper(),
"hydro_observation_date_elab": Identity(),
"hydro_observation_result_elab": Clipper(),
"hydro_status_code": Identity(),
"hydro_qualification_code": Identity(),
"hydro_longitude": Identity(),
"hydro_latitude":  Identity(),
"hydro_hydro_quantity_elab": LabelEncoder(),
"distance_piezo_hydro": Clipper(),
"prelev_volume_0": Clipper(),
"prelev_usage_label_0": LabelEncoder(),
"prelev_volume_obtention_mode_label_0": LabelEncoder(),
"prelev_longitude_0": Identity(),
"prelev_latitude_0": Identity(),
"prelev_commune_code_insee_0": Identity(),
"prelev_volume_1": Clipper(),
"prelev_usage_label_1": LabelEncoder(),
"prelev_volume_obtention_mode_label_1": LabelEncoder(),
"prelev_longitude_1": Identity(),
"prelev_latitude_1": Identity(),
"prelev_commune_code_insee_1": Identity(),
"prelev_volume_2": Clipper(),
"prelev_usage_label_2": LabelEncoder(),
"prelev_volume_obtention_mode_label_2": LabelEncoder(),
"prelev_longitude_2": Identity(),
"prelev_latitude_2": Identity(),
"prelev_commune_code_insee_2": Identity(),
"prelev_other_volume_sum": Clipper(),
"insee_%_agri": Identity(),
"insee_pop_commune": Clipper(),
"insee_%_ind": Identity(),
"insee_%_const":  Identity()
                     }